"""Generate the README live-mode capability matrix from the parity table.

Source of truth: docs/internal/live_parity_v2.md (itself generated by
generate_live_parity.py). This script derives the compact public matrix
the 2026-09-03 live COM stress report asked for and rewrites the README
section between the LIVE_MATRIX markers. Run after any live-routing
change:

    python scripts/generate_live_matrix.py
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PARITY = ROOT / "docs" / "internal" / "live_parity_v2.md"
README = ROOT / "README.md"
START = "<!-- LIVE_MATRIX:START (generated by scripts/generate_live_matrix.py) -->"
END = "<!-- LIVE_MATRIX:END -->"


def parse_rows() -> list[tuple[str, str, str]]:
    rows = []
    for line in PARITY.read_text(encoding="utf-8").splitlines():
        if not line.startswith("| ") or line.startswith("| v2 tool") \
                or line.startswith("|---"):
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        if len(cells) < 3:
            continue
        rows.append((cells[0], cells[1], cells[2]))
    return rows


def short_caveat(behavior: str) -> str:
    """The 'live:' clause of a LIVE-ROUTED row, compressed."""
    m = re.search(r"live: (.+)$", behavior)
    if not m:
        return ""
    text = m.group(1)
    text = text.split(" | ")[0]
    return text


def build_section(rows) -> str:
    live_routed = [(t, short_caveat(b)) for t, _p, b in rows
                   if b.startswith("LIVE-ROUTED")]
    live_native = [t for t, _p, b in rows if b.startswith("LIVE-NATIVE")]
    com_tier = [t for t, _p, b in rows if b.startswith("COM tier")]
    open_reader = [t for t, _p, b in rows
                   if b.startswith("open-document reader")]
    file_writer = sum(1 for _t, _p, b in rows
                      if b.startswith("file-only writer"))
    file_reader = sum(1 for _t, _p, b in rows
                      if b.startswith("file-only reader"))

    out = [START, "## Live-mode capability matrix", ""]
    out.append(
        "Which tools work on a document that is OPEN in Word. Dual-mode "
        "tools auto-route (`live='auto'`); everything else refuses with "
        "`DOCUMENT_LOCKED` until the file is closed. Every COM call is "
        "**serialized server-side** (one call reaches Word at a time), "
        "so concurrent agents queue instead of corrupting; live edits "
        "stay unsaved until `com_save_document` (the Option C model: "
        "see `get_workflows(task='live-editing')`)."
    )
    out.append("")
    out.append("| Dual-mode tool (file + live) | Live-mode notes |")
    out.append("|---|---|")
    for tool, caveat in sorted(live_routed):
        out.append(f"| `{tool}` | {caveat or 'full live support'} |")
    out.append("")
    out.append(
        "**Live-only tools** (need the document open): "
        + ", ".join(f"`{t}`" for t in sorted(live_native))
        + ".  \n**COM tier** (drive the Word application, open or "
        "closed): "
        + ", ".join(f"`{t}`" for t in sorted(com_tier))
        + ".  \n**Open-document reader**: "
        + ", ".join(f"`{t}`" for t in sorted(open_reader))
        + " (reads the last SAVED state and says so)."
    )
    out.append("")
    out.append(
        f"The remaining {file_writer} writers and {file_reader} readers "
        "are file-only: they refuse while the document is open (close it, "
        "or `com_save_document` with `close=true`). The full per-tool "
        "table lives in `docs/internal/live_parity_v2.md`."
    )
    out.append(END)
    return "\n".join(out)


def main() -> None:
    section = build_section(parse_rows())
    readme = README.read_text(encoding="utf-8")
    if START in readme:
        pattern = re.compile(
            re.escape(START) + r".*?" + re.escape(END), re.DOTALL
        )
        readme = pattern.sub(section, readme)
    else:
        anchor = "## Known limits"
        assert anchor in readme, "README anchor '## Known limits' missing"
        readme = readme.replace(anchor, section + "\n\n" + anchor, 1)
    README.write_text(readme, encoding="utf-8", newline="\n")
    print("README live matrix updated "
          f"({len(parse_rows())} parity rows in)")


if __name__ == "__main__":
    main()
